# Generated by Django 3.0.3 on 2020-05-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomember',
            name='PhotoNumber',
            field=models.IntegerField(default=0),
        ),
    ]
