# Generated by Django 3.0.3 on 2020-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_photomember_photonumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoMember',
        ),
    ]
